### ISSUE TITLE
Component doesn't update options when using 'selected' prop

### ISSUE THREAD

**Issue by danpora** [ericgio/react-bootstrap-typeahead#212] opened 2017-07-23 11:21 UTC
### Version
1.4.2

### Steps to reproduce
`<Typeahead
              className="typeahead"
              ref={i === 0 ? 'typeahead' : ('typeahead' + i)}
              onChange={this.onChange.bind(null, i)}
              options={values.options || []}
              selected={values.selected || []}
              placeholder={`add values`}
              multiple={true}
              disabled={!isAttributeSelected}
            />`

### Expected Behavior
I implemented a next button feature: when clicking on the button - I update 'selected' prop to contain the next attribute in 'options' array. After selected is updated - the form shows the actual selected attribute (that's happening and it is ok) and when clicking again on the form, I want to see the new options (after filtered with the updated selected prop).

### Actual Behavior
when clicking on the form, after selected had changed, it still shows the first selected attribute.

**Comment by ericgio** [comment] 2017-07-23 20:32
Hi, thanks for the report. This is a duplicate of #198 and should be fixed in v2.0.0-alpha.1

**Closed by ericgio** 2017-07-23 20:32 UTC
Labels: duplicate
