### ISSUE TITLE
Async fetch and pagination

### ISSUE THREAD

**Issue by andy9775** [ericgio/react-bootstrap-typeahead#221] opened 2017-08-28 19:07 UTC
There seems to be an issue with `AsyncTypeahead` and pagination. I'm fetching a list of data from my backend when a user enters in a search query. My backend also paginates the results (as there can potentially be thousands so I'd like to limit the result count). I'd like to be able to pass in a `paginate={true}` prop whenever there is more data to be fetched from the backend. This doesn't seem to be working at the moment. From what I gather, the default pagination behavior is to paginate on the options that are already provided which doesn't allow the options array to grow. 

Any thoughts on how to go about this?

**Comment by ericgio** [comment] 2017-08-28 20:59
This seems like a duplicate of #143. v1.1 added an `onPaginate` hook that should help you do what you want. Feel free to reopen if I'm misunderstanding something or the functionality doesn't work.

**Comment by andy9775** [comment] 2017-08-28 22:02
Unfortunately it doesn't seem to be working. 
Given the following component
```
  <AsyncTypeahead options={this.state.options}
                      labelKey="id"
                      paginate={shouldPaginate}
                      onPaginate={this.onPaginate}
                      selected={[this.state.selected]}
                      placeholder="Type in a serial number"
                      onChange={this.onItemSelect}
                      onSearch={this.onItemSearch} />
```

with the following functions:

```
  onItemSearch = async (query) => {
    try {
      const result = await api
        .searchItems
        .getAll({
          searchQuery: query,
          limit: this.state.limit,
          offset: this.state.offset,
        });

      this.setState({
        options: this.state.options
          .concat(result.data.results),
          query: query
      });
    } catch (err) {
      console.error(err);
    }

  }
```

```
  onPaginate = () => {
    this.setState({
      offset: this.state.offset + this.state.limit,
      paginateText: 'Searching...',
    }, async () => {
      await this.onItemSearch(this.state.query);
    });
  }
```

`this.state.options` gets filled with new data if I do `console.log(this.state.oprions)` in my render function, but async typeahead never gets updated with the new options. Further, directroy mutating options (`this.state.options.push(...)`) also doesn't work. 

If I set `paginate={true}`, `maxResults={10}` and if `this.state.options.length === 20` it will only display the pagination button once even if the options array grows (`this.state.options.length` grows to 40 after the onPaginate function is called). This results in me only being able to display the initial options data. 

I believe this may be related to #164 it seems like
<hr/>
My current workaround is to use `renderMenu` to create my own wrapper around the data and handle displaying the pagination button on my own. However, I still can't seem to use the `results` argument which means my function looks like:

```
  renderMenu = (results, menuProps) => {
    let component = /* show loading indicator or pagination button*/
    return (
      <Menu {...menuProps}>
        {this.state.options.map(this.renderAircraftMenuItem)}
        {component}
      </Menu>
      );
  }
```
As you can see I have to use `this.state.options` rather than `results` as the results argument doesn't pass the updated data.

**Comment by ericgio** [comment] 2017-10-26 21:39
I dug into this a bit more and the reason you're not seeing the complete set of options is that they don't get added to the cache, which is on by default. If you set `useCache={false}`, you should see the paginated results get populated. I didn't test your code specifically, but I got the Async example working this way.

I'd lean towards calling this a bug, since it feels like the cached results should update.

**Comment by andy9775** [comment] 2017-10-30 01:45
Hey, `useCache={false}` fixed the issue and I agree, seems to me like it should work with cached results.

**Comment by ericgio** [comment] 2017-10-30 19:28
After thinking about it some more, my feeling is that the built-in cache is for basic use cases and pagination falls outside of that. You'd need to make a lot of assumptions about how the pagination works so I think that's best left to the developer. I added a [pagination example](https://github.com/ericgio/react-bootstrap-typeahead/blob/2.0/example/examples/AsyncPaginationExample.js) as one possible solution, but I imagine there could be lots of variations.

**Closed by ericgio** 2017-10-30 19:28 UTC
Labels: async
