### ISSUE TITLE
New options through `allowNew` should be selectable on enter

### ISSUE THREAD

**Issue by corneliusroemer** [ericgio/react-bootstrap-typeahead#655] opened 2021-07-04 14:01 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated, that I can't select a new selection with enter. Allow new is good, but it should also become a hint, so that it can be selected by enter.

```
allowNew={true} 
selectHintOnEnter={true} 
```

The need for this popped up in this issue:
https://github.com/cevo-public/cov-spectrum-website/issues/173#issuecomment-873592385

**Describe the solution you'd like**
When allow new is set, it should be possible for the new option to be shown as a hint. Maybe there should be a new prop: `allowNewAsHint`

**How is this solution useful to others?**
It improves keyboard navigability and usability for new options

**Describe alternatives you've considered**
I don't know of a good work around

**Comment by ericgio** [comment] 2021-07-04 18:25
Hi @corneliusroemer, thanks for raising this issue. I think this is essentially a duplicate of #505 so I'm going to close this issue in favor of that one.

**Closed by ericgio** 2021-07-04 18:25 UTC
Labels: feature request

**Comment by corneliusroemer** [comment] 2021-07-04 18:48
Sounds similar indeed, though I don't know enough about Typeahead to say whether it's identical. In any case, it'll be referenced from there.
