### ISSUE TITLE
ID attribute is ignored

### ISSUE THREAD

**Issue by martinsvoboda** [ericgio/react-bootstrap-typeahead#629] opened 2021-03-23 14:02 UTC
Required attribute id, do not propagate to HTML element - attribute id is ignored. This means is not possible to anchor label with input.

### Version

react-bootstrap-typeahead@5.1.4

### Steps to reproduce

```<AsyncTypeahead id="test" />```

### Expected Behavior

Rendered input HTML should contain id="test":

```<input ... id="test">```

### Actual Behavior

Input doesn't contain attribute id.

### Workaround

```<AsyncTypeahead inputProps={{id: "test"}} />```

**Comment by ericgio** [comment] 2021-03-23 15:49
Duplicate of #628 and others

**Closed by ericgio** 2021-03-23 15:49 UTC
Labels: bug
