### ISSUE TITLE
korean letters are not properly combined in 2.0

### ISSUE THREAD

**Issue by dantzchan** [ericgio/react-bootstrap-typeahead#254] opened 2017-10-23 01:30 UTC
### Version
2.0 
### Steps to reproduce
try to type any korean word
### Expected Behavior
<img width="898" alt="2017-10-23 10 23 21" src="https://user-images.githubusercontent.com/13914133/31868640-5e203240-b7dc-11e7-853f-6718bf85baed.png">
korean words are expected to be combined like the above ( ss taken from master branch example page) 

### Actual Behavior
<img width="892" alt="2017-10-23 10 22 33" src="https://user-images.githubusercontent.com/13914133/31868663-b4f75dfa-b7dc-11e7-96c7-1f09713cad67.png">
(ss from 2.0 example page)
korean words are broken down into letters, not creating any words

**Comment by ericgio** [comment] 2017-10-23 16:06
Thanks for the report. I can't write Korean, so I tried reproing by copy-pasting text from a Korean website and the text showed up fine as far as I could tell. Can you a) confirm that copy-pasting works as expected, and b) provide some more specific steps I can follow to debug?

**Comment by dantzchan** [comment] 2017-10-24 09:35
Copy pasting does get the correct word into the input field. I don't know how to reproduce this without typing Korean though. I'll try to find which changes from v1 to v2 cause this behavior.

**Comment by ericgio** [comment] 2017-10-24 17:41
@dantzchan: Thanks for the help. If I had to guess, I'd suspect it has something to do with the use of `react-input-autosize` for the single-selection case in v2.0. An easy way to test this theory is to try and repro in the v1 example with "Multi-select" checked, since that uses the autosize input.

**Comment by ericgio** [comment] 2017-11-01 08:57
Looks like this bug was actually related to several other issues I was seeing with cursor positioning. It was fixed with [this commit](https://github.com/ericgio/react-bootstrap-typeahead/commit/cf247c1503594f177302f10b412aa3588669e968) and released in v2.0.0-rc.2.

I was able to switch my keyboard to Korean and get the individual letters to combine as expected. Checking out the prior commit and re-testing reproduced the issue. I think we should be all good here, but let me know if you notice any other weirdness.

**Closed by ericgio** 2017-11-01 08:57 UTC
Labels: bug, need info
