### ISSUE TITLE
Multiple TextInput onClick moves cursor to the end of the word if no option is selected.

### ISSUE THREAD

**Issue by seppulcro** [ericgio/react-bootstrap-typeahead#615] opened 2021-02-02 15:45 UTC
### Version
5.1.4 // any

### Steps to reproduce
Using **Multiple**
https://ericgio.github.io/react-bootstrap-typeahead/#basic-example
https://codesandbox.io/s/9jq9jyzmry?file=/src/index.js

1. Type Aryzhona in the text input.
2. Use your mouse to click either the "y" or the "h" in "Aryzona" to try and remove it out.

### Expected behavior
While typing a word in a **multiple** component, use the mouse to place the cursor somewhere in the word, or select part of it to remove/edit.

### Actual behavior
When the user clicks somewhere using his mouse on the current word option the cursor is placed at the end of the word and won't allow any selection. You use the keyboard's arrow keys to place the cursor and select parts of the word, but the mouse always pushes the cursor to the end of the word. (This affects mobile users).
You either delete the whole word or use the keyboard to reach the character index you want to edit/add.

**Comment by ericgio** [comment] 2021-02-03 05:14
Thanks for the bug report @seppulcro, I can reproduce the issue. Looks like the click event bubbles up to the container, which moves the cursor to the end of the string.

**Comment by ericgio** [comment] 2021-07-09 08:52
Fixed in v5.2.0

**Closed by ericgio** 2021-07-09 08:52 UTC
Labels: bug
