### ISSUE TITLE
Where is the Typeahead search box value stored

### ISSUE THREAD

**Issue by AllanCodes** [ericgio/react-bootstrap-typeahead#319] opened 2018-02-22 16:52 UTC
I would like to have a long string being entered such as 
`pg >= 1 and pl < 10 or kp > 5`

I would like pg, pl and kp to be suggested when typed in this line.  As of now, after pg it just says no suggestion found.  Is there anything to do for this?

**Comment by ericgio** [comment] 2018-02-22 17:43
I'm not sure I understand your question. Are you saying the user input is "pg >= 1 and pl < 10 or kp > 5" and you want the component to parse that string and suggest "pg", "pl" and "kp"?

Code examples would be helpful.

**Comment by AllanCodes** [comment] 2018-02-22 18:05
I actually do the parsing already after the string is unfocused with the onBlur.  My issue is that for example this is something the user will type: `pg >= 1 and pl < 10 or kp > 5`

pg, pl and kp are so called features in my program that will need to be suggested.

As you type pg, the suggestions will pop up.  We continue typing.  pg >= 1 and pl.  At this point suggestions pop up again.  We keep typing.  pg >=1 and pl < 10 or kp.  At this point suggestions pop up to suggest kp.  We finish typing.

So it's like I have certain names I'd like to be suggested throughout a line that is being typed so that the user doesn't have to reference them else where.  Is this more clear?

**Comment by ericgio** [comment] 2018-02-22 18:17
It sounds like you want to use the typeahead to build a phrase by autocompleting fragments, which it's not really designed to do. This component is more for filtering down a set of options based on the user input. You might be able to approximate the functionality you want through some combination of a custom `filterBy` function, and the `allowNew` property, but I'm not sure.

**Comment by ericgio** [comment] 2018-02-26 16:56
Closing out since it's not a bug and likely out of scope as a feature request.

**Closed by ericgio** 2018-02-26 16:56 UTC
