### ISSUE TITLE
onMulti select the cursor jumps to the typed content.

### ISSUE THREAD

**Issue by arvind0364** [ericgio/react-bootstrap-typeahead#650] opened 2021-06-02 15:42 UTC
when am enabling multiple to TRUE am facing this weird issue.

Steps :
    If I key in USA and keep my cursor in between U and S my cursor jumps back to end of content.

  attached a simple codesandbox here : https://codesandbox.io/s/holy-voice-yzxvv?file=/src/index.js
  
 Please take a look at it and help me to arrive at a solution. Thanks.!

**Comment by ericgio** [comment] 2021-06-03 01:15
Hi @arvind0364, thanks for filing this issue. Unfortunately, I'm not able to repro the problem based on your description; can you please provide more specific steps? Thank you!

**Comment by arvind0364** [comment] 2021-06-03 05:28
https://user-images.githubusercontent.com/57353932/120591829-70975a00-c45a-11eb-9d9c-013c64c0eaba.MOV

@ericgio I have attached a video reference you can clearly see how the cursor jumps to the end.

**Comment by ericgio** [comment] 2021-06-06 18:50
Thanks for the screencap, I see what you're talking about. There's a handler on the input container to make clicks focus the input. It sets the cursor position to be the end of the value, but shouldn't override the cursor position if the click happens on the input itself.

**Comment by arvind0364** [comment] 2021-06-07 06:28
Is there any fix for it.?

**Comment by ericgio** [comment] 2021-06-07 06:31
It's a bug. You can use the arrow keys to move to the desired cursor position.

**Comment by ericgio** [comment] 2021-07-09 05:22
Looking again, this appears to be a duplicate of #615, closing in favor of that issue.

**Closed by ericgio** 2021-07-09 05:22 UTC
Labels: bug
