### ISSUE TITLE
Internet Explorer issues since v2

### ISSUE THREAD

**Issue by seriousManual** [ericgio/react-bootstrap-typeahead#286] opened 2018-01-08 11:56 UTC
Since v2 there are some styling/formatting bugs in several versions of Internet Explorer.

Edge:
The first entered letter is truncated.

IE11:
When entering text the font size changes eratically, key presses are swallowed up from time to time.

Until version 2 this worked fine.

### Version
v2.0.2

### Steps to reproduce
Enter text in Typeahead component via IE 11 / Edge

**Comment by ericgio** [comment] 2018-01-08 18:00
Hi and thanks for the report. I'm not able to reproduce these issues using [the examples](http://ericgio.github.io/react-bootstrap-typeahead/). Can you please provide more specific repro steps? Are you seeing the issue using the examples or in your own implementation? If the latter, do you have any CSS that's overriding the default styles? Thanks.

**Comment by ericgio** [comment] 2018-01-08 18:10
Actually, I have occasionally noticed the issue where characters are slightly cut off. This usually only happens with wider, angled characters like "A" or "W". Does that match up with what you're seeing?

**Comment by ericgio** [comment] 2018-04-04 17:27
I don't repro these issues. Closing, but feel free to re-open with more detailed instructions.

**Closed by ericgio** 2018-04-04 17:27 UTC
