### ISSUE TITLE
Integrating Popper.js to manage menu position

### ISSUE THREAD

**Issue by Guymestef** [ericgio/react-bootstrap-typeahead#281] opened 2017-12-20 15:08 UTC
Feature requests
=======================
Integrating Popper.js to manage menu position as bootstrap do, would be a better idea than using the dropup prop.
Good or bad idea?

**Comment by Guymestef** [comment] 2017-12-20 15:09
Popper.js lib: https://github.com/FezVrasta/popper.js/#react-vuejs-angular-angularjs-emberjs-etc-integration

**Comment by ericgio** [comment] 2017-12-23 21:04
The main thing this would address is #125.

> a better idea than using the dropup prop

Note that Bootstrap still incorporates an explicit [dropup version](https://getbootstrap.com/docs/4.0/components/dropdowns/#dropup-variation).

**Comment by ericgio** [comment] 2018-01-14 08:49
Closing this as more or less a dupe of #125.

**Closed by ericgio** 2018-01-14 08:49 UTC

**Comment by ericgio** [comment] 2018-04-04 17:40
As of v3.0.0 the component uses Popper.js (via `react-popper`) for positioning. Thanks for the suggestion!
