### ISSUE TITLE
Missing result when sorting options based on onInputChange

### ISSUE THREAD

**Issue by devjefe** [ericgio/react-bootstrap-typeahead#487] opened 2019-09-18 16:30 UTC
I'm trying to sort options based on onInputChange, and the rendered menu is consistently missing the last result. I.E.  Connecticut when input is u, or California for i. 

<img width="528" alt="Screen Shot 2019-09-18 at 12 28 33 PM" src="https://user-images.githubusercontent.com/33466405/65167077-dd14c000-da0f-11e9-86fb-7563699c665f.png">
<img width="305" alt="Screen Shot 2019-09-18 at 12 28 24 PM" src="https://user-images.githubusercontent.com/33466405/65167078-dd14c000-da0f-11e9-9872-a7d8aacf883b.png">

### Version
 3.4.7

### Steps to reproduce

```jsx
function Sorter() {
  const [opts, setOpts] = useState(states);

  const sortOpts = search =>
    opts.sort(function(a, b) {
      const matchA = a.toLowerCase().indexOf(search);
      const matchB = b.toLowerCase().indexOf(search);
      console.log(matchA);
      if (matchA < 0) {
        return 1;
      } else if (matchB < 0) {
        return -1;
      } else return matchA - matchB;
    });

  const handleInputChange = e => {
    let sortedOps = sortOpts(e);
    console.log(e);
    console.log(sortedOps);
    setOpts(sortedOps);
  };

  console.log(opts);
  return (
    <Autocomplete
      minLength={1}
      name="test"
      placeholder="Choose a state..."
      options={opts}
      onInputChange={e => handleInputChange(e)}
    />
  );
}

```
### Expected Behavior

Return all results

### Actual Behavior
Returning all but last, or 9th index result.

**Comment by ericgio** [comment] 2019-09-18 19:03
Hi @devjefe, thanks for reporting this issue. I created a sandbox with a modified version of your code (using state instead of hooks) and was not able to reproduce the issue:

https://codesandbox.io/s/react-bootstrap-typeahead-issue-487-1ygjw

It's possible that the library has some issues with hooks, but I'm not sure. Can you either update the sandbox above or provide a new one reproducing the issue? Thanks!

**Comment by devjefe** [comment] 2019-09-18 20:08
@ericgio Thanks so much for taking the time to attempt a reproduce. I added both examples side by side in the codepen and they both work! 

https://codesandbox.io/s/react-bootstrap-typeahead-issue-487-cw653?fontsize=14

As you can probably tell I'm building a reusable Autocomplete component where I'm just passing all the props through to your Typeahead, it must be a props issue and likely not a bug. But if I do spot any issues with hooks as I incorporate more features I'll keep you posted!

**Comment by ericgio** [comment] 2019-09-18 20:25
Thanks for the update @devjefe. I'll close this issue for now, but please re-open if you discover that there is in fact a bug in the library.

**Closed by ericgio** 2019-09-18 20:25 UTC
Labels: bug
