### ISSUE TITLE
React warning - componentWillReceiveProps

### ISSUE THREAD

**Issue by Belsi** [ericgio/react-bootstrap-typeahead#498] opened 2019-10-24 07:16 UTC
### Version
"react-bootstrap-typeahead": "3.4.7",
"react": "16.9.0",

### Description

Please update to new React.

### In console

`react-dom.development.js:12466 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TypeaheadContainer(WrappedTypeahead)`

**Comment by ericgio** [comment] 2019-10-24 16:40
Duplicate of #415

**Closed by ericgio** 2019-10-24 16:40 UTC
Labels: bug
