### ISSUE TITLE
multiple does not work in combination with placeholder

### ISSUE THREAD

**Issue by derwaldgeist** [ericgio/react-bootstrap-typeahead#238] opened 2017-10-03 21:35 UTC
### Version

1.4.2

### Steps to reproduce

Create a Typeahead with `multiple` and `placeholder`

### Expected Behavior

The placeholder shows up correctly, if the field is empty and unfocused.

### Actual Behavior

If the field is unfocused, only a small part of the placeholder is shown (2px wide). If you focus the field, the placeholder shows up correctly. This is because before focus the input with class `bootstrap-typeahead-input-main` is forced to be 2px wide by applying an inline style.

If the field unfocuses again, everything is fine. It seems as if the width of the placeholder is somehow calculated as soon as the cursor is being placed inside the field for the first time, but not before this timepoint.

I tried to use autoFocus to workaround this, but this didn't work either.

**Comment by ericgio** [comment] 2017-10-05 07:18
Thanks for the bug report. I'm no longer making updates to 1.x. This shouldn't be an issue in v2.0, however. If you can confirm that's the case, I'll close this out.

**Comment by ericgio** [comment] 2017-10-05 07:22
By the way, I don't repro this behavior. The [very first example](http://ericgio.github.io/react-bootstrap-typeahead/#basic-example) uses a placeholder with `multiple` and works fine.

**Comment by derwaldgeist** [comment] 2017-10-05 07:52
Yes, I have seen the example worked. But I wasn't sure whether this was already using 2.x. Strange that this only happens in my app.

**Comment by derwaldgeist** [comment] 2017-10-05 08:06
Is it safe to use 2.x already? I am asking since it is still labelled as "alpha".

**Comment by derwaldgeist** [comment] 2017-10-05 08:20
I updated to the most recent 2.x version, and now the same problem applies to all search fields, i.e. also those which are not marked with `multiple`.

BTW: Was there a specific reason why in 2.x all class names have been renamed to `rbt-`? I think this increases the risk of clashes with other class names as `rbt` is quite short. There's also a lot of inline styling happening which makes it very hard to customize the design of the input. I would prefer if css styles were being used instead where possible. The reason I have applied custom styling is that I want to mimick the look and feel of iOS input fields which are quite different.

**Comment by ericgio** [comment] 2017-10-07 01:33
This seems like an issue with whatever styles you're applying to the component.

> Was there a specific reason why in 2.x all class names have been renamed to rbt-? I think this increases the risk of clashes with other class names as rbt is quite short.

Only a couple styles rely on `.rbt` alone. All the others have `.rbt-{something}`, so it seems unlikely that this will conflict with things. But the classname change is called out as a breaking change in the release notes just in case.

> There's also a lot of inline styling happening which makes it very hard to customize the design of the input. I would prefer if css classes were being used instead where possible.

Pretty much all the inline styles are necessary for the typeahead to work as intended, and probably shouldn't be overridden. These are primarily for behaviors as opposed to appearance. Also, the component uses `react-input-autosize` (which you seem to be having some trouble with), which applies a lot of inline styles and I don't have much control over that.

> Tt would be cool if the SCSS files were included in the dist build, too, so they could be used instead to customize the look and feel directly.

You can just customize the css file directly as well. It also seems easy enough to copy the scss file directly from the repo.

**Closed by ericgio** 2017-10-07 01:33 UTC

**Comment by ajaykgp** [comment] 2018-04-13 08:39
I am facing the same issue and couldn't find a solution to this. @derwaldgeist How did you solve the issue?
