### ISSUE TITLE
Can't remove input character on iOS

### ISSUE THREAD

**Issue by danielholmes** [ericgio/react-bootstrap-typeahead#257] opened 2017-10-30 03:36 UTC
### Version

2.0.0-alpha.6

### Steps to reproduce

1. Open [https://codesandbox.io/s/m5oqlq2wox](https://codesandbox.io/s/m5oqlq2wox) in Safari or Chrome on iOS (example is a plain react 16, bootstrap css and typeahead component setup)
2. Focus the input
3. Type a single letter (e.g. "F")
4. Press backspace to try and remove the "F"

### Expected Behavior

The "F" is removed and the input is clear

### Actual Behavior

The "F" remains

### Notes

- This doesn't occur in 1.4.2. See [https://codesandbox.io/s/q9p35rvv7w](https://codesandbox.io/s/q9p35rvv7w)
- The issue is related to the last character typed. e.g. type "Face" instead then try and backspace all the characters, the "e" will remain
- From what I've seen, this is only on iOS. I've replicated it in an xcode iOS simulator for iOS 11 on iphone, on a physical iPhone 5 under iOS 10 and on an iPad Air running iOS 11
- Happens for both standard and Asynchronous typeaheads

**Comment by ericgio** [comment] 2017-10-30 16:31
Thanks for the report, and for the detailed explanation and repro steps. I can also repro the issue. I suspect this is related to #229, possibly caused by the code I added to fix that issue. Not sure why it would behave differently on iOS, though.

**Comment by ericgio** [comment] 2017-10-31 17:10
This should be fixed as of v2.0.0-rc.2

**Closed by ericgio** 2017-10-31 17:10 UTC
Labels: bug
