### ISSUE TITLE
React-bootstrap Typeahead does not work with Jest snapshots

### ISSUE THREAD

**Issue by oliverwatkins** [ericgio/react-bootstrap-typeahead#489] opened 2019-10-02 11:31 UTC
Note I posted the same issue in StackoverFlow here :

https://stackoverflow.com/questions/58199979/react-bootstrap-typeahead-does-not-work-with-jest-snapshots

### Version
v3.4.7

### Steps to reproduce

- create a simple typeahead example
- create a jest snapshot test

```
import React from 'react';
import renderer from "react-test-renderer";
import AsyncTest from "./AsyncTest";

describe('Async Test', () => {
    test('test', () => {
        const test= <AsyncTest/>
        expect(renderer.create(test).toJSON()).toMatchSnapshot();
    });
});
```

```
import {AsyncTypeahead} from "react-bootstrap-typeahead";
import React, {Component} from "react";

    class AsyncTest extends Component<Props, State> {
        constructor() {
            super()
            this.state = {
                isLoading:false,
                options:{}
            }
        }
        render() {
            return <AsyncTypeahead
                disabled={true}
                isLoading={this.state.isLoading}
                onSearch={query => {
                    this.setState({isLoading: true});
                    fetch(`https://api.github.com/search/users?q=123`)
                        .then(resp => resp.json())
                        .then(json => this.setState({
                            isLoading: false,
                            options: json.items,
                        }));
                }}
                options={this.state.options}
            />
        }
    }

export default AsyncTest;
```

### Expected Behavior

It should not fail.

### Actual Behavior
```
TypeError: Cannot read property 'style' of null

at Window.getComputedStyle (A:\frontend\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\browser\Window.js:524:20)
at copyStyles (A:\frontend\node_modules\react-bootstrap-typeahead\lib\containers\hintContainer.js:61:27)
at HintedInput.componentDidMount (A:\frontend\node_modules\react-bootstrap-typeahead\lib\containers\hintContainer.js:113:9)
at commitLifeCycles (A:\frontend\node_modules\react-test-renderer\cjs\react-test-renderer.d
```

**Comment by ericgio** [comment] 2019-10-02 16:36
Hi @oliverwatkins, thanks for reporting this issue. Based on [this SO answer](https://stackoverflow.com/a/40854433/882638), I believe your problem is caused by how react-test-renderer works, not by this library:

> Since test renderer is not coupled to React DOM, it doesn't know anything about what refs are supposed to look like. React 15.4.0 adds the ability to mock refs for test renderer **but you should provide those mocks yourself**. Note that it only works with React 15.4.0 and higher.

I'm going to close this issue, but please let me know if further investigation leads you to believe there's an actual bug in the library here.

**Closed by ericgio** 2019-10-02 16:36 UTC
Labels: bug

**Comment by oliverwatkins** [comment] 2019-10-04 09:42
I tried using the createNodeMock, and i can succesfully mock out the style object from the INPUT, but now it crashes because of 

> [TypeError: Cannot read property '_ownerDocument' of undefined]

Not sure why its doing that :/

**Comment by cworsley4** [comment] 2019-12-18 18:17
@oliverwatkins did you ever get to the bottom of this?
