### ISSUE TITLE
Multiple Typeaheads not Closing Other Typeaheads (React 17)

### ISSUE THREAD

**Issue by dleavitt** [ericgio/react-bootstrap-typeahead#695] opened 2022-02-14 21:19 UTC
### Version

react-bootstrap-typeahead 5.2.1 (6.0.0-alpha.8 also affected)
react 17.0.1
react-dom 17.0.1

### Steps to reproduce

Go here: https://codesandbox.io/s/rbt-multi-not-closing-forked-ppj01

- Click on the bottom (third) typeahead
- Click on the middle (second) typeahead

### Expected Behavior

The third typeahead should close.

### Actual Behavior

The third typeahead stays open, obscuring the second.

Behaves as expects when:
- Using React 16.x
- Opening a typeahead where `multiple={false}`
- Clicking anywhere else on the page.

![Screen Shot 2022-02-14 at 13 16 57](https://user-images.githubusercontent.com/71686/153947786-e9f6fcbf-c105-49b7-8a41-d2a90f7ed697.png)

**Comment by ericgio** [comment] 2022-02-15 23:24
Hi @dleavitt, thanks for the report! I can confirm the behavior you describe, and it looks like the bug is happening with v6 of this library as well. The problem most likely has something to do with [changes to event delegation in React 17](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation) but I'll need to dig a little deeper.

**Comment by ericgio** [comment] 2022-02-16 21:33
The bug is happening because `TypeaheadInputMulti` relies on `e.stopPropagation` for some of its behaviors. Prior to v17, `stopPropagation` [would still bubble up to listeners on the `document`](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#:~:text=If%20you%20have,four%20years%20ago.), and the typeahead relied on that to achieve the desired menu behavior. With React 17, `stopPropagation` works as expected and truly stops the event from bubbling up, so the click is no longer registered and the menu doesn't close, as you've observed.

**Comment by ericgio** [comment] 2022-02-16 21:58
Fixed in v5.2.2 and v6.0.0-alpha.9

**Closed by ericgio** 2022-02-16 21:58 UTC
Labels: bug

**Comment by dleavitt** [comment] 2022-02-24 22:03
thanks so much + appreciate the explanation!
