### ISSUE TITLE
Dynamically set input size or give an optional use in text-area instead

### ISSUE THREAD

**Issue by laviro** [ericgio/react-bootstrap-typeahead#504] opened 2019-11-27 13:13 UTC
first of all, thank you for all of the great work that you've done !

**Is your feature request related to a problem? Please describe.**
When the search query gets too long I wonder if there's a way to dynamically adjust it to the text size, or as an alternative give an option to use a text-area?

**Describe the solution you'd like**
Add an ability to dynamically adjust the input size to the text size, or as an alternative give an option to use a text-area.
**How is this solution useful to others?**
yes

**Describe alternatives you've considered**
adjust its css styles to fit the text content.

**Additional context**
https://github.com/theforeman/foreman_remote_execution/pull/454

before using the React component there was a text-area:
![](https://user-images.githubusercontent.com/7326770/69725596-ce890a00-111e-11ea-97e9-249a907fd154.png)

after using the React component:
![](https://user-images.githubusercontent.com/7326770/69724089-68e74e80-111b-11ea-94fa-17441c94d1c5.png)

**Comment by ericgio** [comment] 2019-11-27 18:00
Hi @laviro, thanks for filing this issue. It looks like you have a few things going on here:

1. **Hint overflows the text input**: This is documented in #473. You should be able to resolve that fairly easily with some CSS.
2. **Long hint doesn't align with input text**: Also addressed in #473. As noted there, this is a tougher problem to solve, and I'm not sure if it's possible. If this is a real problem for you, you may want to disable the hint (via CSS).
3. **Long menu items**: It looks like you're using `align="left"`, in which case the menu items will stretch to the length of their contents. If you use the default (`align="justify"`), the menu will be the width of the input and the menu items will be truncated accordingly. If you need more control over rendering of the menu items, use the `renderMenu` prop to customize the menu.

Giving the input a dynamic width or using a `textarea` instead of an `input` are not things I plan on adding out of the box. However, v4 (currently in alpha) adds a `renderInput` method that provides full flexibility over rendering of the input element. I've never tried using a `textarea` so I have no idea how well that would work, but give it a shot!

**Comment by laviro** [comment] 2019-12-02 14:52
Thanks for your comment @ericgio,
maybe we could pass a special prop to fix the *Hint overflows the text input* ?

can't wait to that v4 ! sounds awesome :+1:

**Comment by ericgio** [comment] 2019-12-02 17:22
> maybe we could pass a special prop to fix the Hint overflows the text input

Not exactly sure what you mean by that, but you can pass a classname to the component to scope your CSS if you need to.

**Comment by ericgio** [comment] 2019-12-02 17:24
I'm going to close this issue as a duplicate of #473, but feel free to provide more information if you think I'm missing anything.

**Closed by ericgio** 2019-12-02 17:24 UTC
Labels: feature request
