### ISSUE TITLE
found an UI glitch

### ISSUE THREAD

**Issue by xmluozp** [ericgio/react-bootstrap-typeahead#857] opened 2024-07-18 19:18 UTC
When the text inside options are too long, the first render will make the dropdown box on wrong position
![image](https://github.com/user-attachments/assets/5cc94d2d-48ea-4982-a38f-b169973522b6)

direct cause:
when first render. the container calculates the "translate" based on width of the option box. In my case its:
    transform: translate(-263px, 38px);

however its based on oversized text box (the class ".dropdown-item") which causes the issue.
once you scroll it, then it will be auto adjusted.

my current workaround is to hardcode width of ".dropdown-item"

**Comment by ericgio** [comment] 2024-07-18 21:33
Thanks @xmluozp! I believe this is a duplicate of #776.

**Closed by ericgio** 2024-07-18 21:33 UTC
Labels: bug
