### ISSUE TITLE
filterBy (true), onSearch and caseSensitive (false)?

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#606] opened 2020-12-05 17:23 UTC
I am use AsyncTypeahead and disable filtering - filterBy={()=>true}, onSearch method return my list from dataBase. This is good work. But if I input value from keyboard - TypeAhead filter list with caseSensitive=true allways.

How can I use filterBy props and caseSensitive={false} ? Thanks

**Comment by ericgio** [comment] 2020-12-05 18:05
Hi @GABuryan, thanks for the question. I don't understand your issue, since bypassing the `filterBy` callback also bypasses case sensitivity. Do you mean that you want to retain the case-sensitive filtering? A sandbox reproducing your issue, code examples, or a better description of your problem would be helpful.

**Comment by GABuryan** [comment] 2020-12-05 18:15
I want to see the full list of values always in the drop down menu. Without fiterBy(true) if I selected a value, there will only be one item in the menu. To see the rest of the values in the menu I have to clear the input field.  filterBy (true) resolved my problem. I always see in dropdown menu all list items. But stop working props - caseSensitive.

**Comment by GABuryan** [comment] 2020-12-05 18:22
I see all list if if I click on the input field.
Example

 ```
handleFocus() {
    const { options, isLoading } = this.state;
    if (options.length === 0 && !isLoading) {
         this.handleSearch();
    }
   
  }
<AsyncTypeahead
        ..
    onFocus={this.handleFocus}
    onChange={this.handleChange}
    onSearch={this.handleSearch}
```

**Comment by GABuryan** [comment] 2020-12-05 18:27
with filterBy and select value, click on input

![image](https://user-images.githubusercontent.com/63857390/101260393-96a89f80-3740-11eb-8da8-a01ca7a7c1c5.png)

**Comment by GABuryan** [comment] 2020-12-05 18:28
without filterBy and select value, click on input in menu only "003" value

**Comment by GABuryan** [comment] 2020-12-05 18:36
Clicked mouse I see all list item (without filtering), if keyboard input then typeahead filtered values in list, but with filterBy caseSensitive not work.

**Comment by ericgio** [comment] 2020-12-05 22:49
@GABuryan: As noted in [the docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#option-objectstring-props-object--boolean), overriding the default `filterBy` callback ignores the `caseSensitive` and `ignoreDiacritics` functionality. If you want your filtering to be case-sensitive, you'll need to add that back into your `filterBy` function.

**Comment by GABuryan** [comment] 2020-12-06 05:02
I uderstand this. But filterBy={()=>true} does not require additional conditions.
Example:
In my DataBase records: 
 - Abdul
- Gabdul
- Ivan

<AsyncTypeahead
 filterBy={()=>true}
 onSearch=..

I type in Input: "ab" or "Ab" or "AB"

onSearch allways return in selected=["Abdul","Gabdul"]

but in Dropdown Menu if "ab" I see "Gabdul", if "Ab" - "Abdul", if "AB" - nothing
 I want to see in Dropdown "Abdul", "Gabdul"

AsyncTypeahead without  filterBy
I type in Input: "ab" or "Ab" or "AB"

onSearch allways return in selected=["Abdul","Gabdul"]

Dropdown always "Abdul", "Gabdul". This good. But if I selected "Abdul" from list and click on Input, then I see only "Abdul"
My goal - click mouse: see all list from database (filterBy={()=>true}). But if I typed on keyboard list search with caseSensitive (false). This work only without filterBy.

I

**Comment by ericgio** [comment] 2020-12-06 05:46
@GABuryan: can you please post a minimal repro case? I can't reproduce your issue when using the [async example](http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching).

**Comment by GABuryan** [comment] 2020-12-06 06:02
Hm..Different minLengt={0} onFocus={this.handleFocus}

handleFocus() {
    const { options, isLoading } = this.state;
    if (options.length === 0 && !isLoading) {
         this.handleSearch();
    }
  }

User click mouse in empty input - list not empty. In my case Database return max 2000 records always. 

the user can start writing immediately or click and select. If he doesn't see it among the entries, he will start writing in input

Иut maybe I don't see a mistake, I'll think thank you

**Comment by ericgio** [comment] 2020-12-06 06:08
I don't think there's a bug here, so I'm going to close this issue. If you can provide a reproducible example, I'm happy to reopen and investigate further.

**Closed by ericgio** 2020-12-06 06:08 UTC

**Comment by GABuryan** [comment] 2020-12-06 06:37
Yes, my bug. I thought it returned true always...But sometimes there was a refund by condition 
return option[labelKey].indexOf(props.text) !== -1;

I replaced on - return option[labelKey].toLowerCase().indexOf(props.text.toLowerCase()) !== -1;

Thanks for ref - this helped me
