### ISSUE TITLE
Is there a way to render a table as a menu?

### ISSUE THREAD

**Issue by lourenci** [ericgio/react-bootstrap-typeahead#466] opened 2019-07-16 16:27 UTC
Hi, thanks for the library.

I'm struggling with the component trying to render a `table` instead a `ul`. I want to try something like that:

![image](https://user-images.githubusercontent.com/2339362/61311787-72f05c80-a7cd-11e9-97b5-ce51b8b5e252.png)

Could you please give me a hint about that?

Thank you.

**Comment by ericgio** [comment] 2019-07-16 18:06
Hi @lourenci, I've never tried to render a table in the menu so I'm unable to help you, sorry. However, I don't see why it can't be done. I'm going to close this issue since it's a usage question and not a bug report or feature request. Let me know if you feel otherwise, though.

**Closed by ericgio** 2019-07-16 18:06 UTC
