### ISSUE TITLE
Using state to store the current value in `onInputChange` prevents `onSearch` from being called.

### ISSUE THREAD

**Issue by SteppingHat** [ericgio/react-bootstrap-typeahead#769] opened 2023-03-02 06:18 UTC
### Version

6.0.2

### Steps to reproduce

This issue is when trying to use state to track the currently entered value by using the `onInputChange` callback, the `onSearch` callback is prevented from being called.

```typescript
import React, {useEffect, useState} from "react";
import axios from "axios";
import {Typeahead} from "react-bootstrap-typeahead";

interface Props {
    url: string;
    initialValue: string;
}

interface SearchResponse {
    id: number;
    name: string;
}

const cachedResults = new Map();

const TestPicker: React.FC<Props> = ({initialValue = '', ...props}) => {
    const [isLoading, setIsLoading] = useState(false);
    const [items, setItems] = useState<SearchResponse[]>([]);
    const [value, setValue] = useState(initialValue);

    const handleSearch = (query: string) => {
        setItems([]);
        query = query.toLowerCase();

        if(cachedResults.has(query)) {
            setItems(cachedResults.get(query));
            setIsLoading(false);
        } else {
            const result = await search(query);
            setItems(result);
            setIsLoading(false);
            cachedResults.set(query, result);
        }
    }

    async function search(query: string): Promise<SearchResponse[]> {
        const response = await axios.get(props.url, {params: {'q': search}});
        return response.data.results;
    }

    return (
        <div>
            <Typeahead
                filterBy={() => true}
                caseSensitive={false}
                id={props.name}
                isLoading={isLoading}
                labelKey={(item: SearchResponse) => item.name}
                onInputChange={(query) => {
                    setIsLoading(true);
                    setValue(query);    // <-- this line, and this line only prevents a search from happening
                }}
                onChange={(organisations: SearchResponse[]) => {
                    if(organisations.length != 1) return
                    setValue(organisations[0].name);
                }}
                onSearch={handleSearch}
                options={items}
                defaultInputValue={initialValue}
            />
        </div>
    )
```

### Expected Behavior

I expect that each time the input is changed, `value` is instantly updated, and then after the default delay a search query is made.

### Actual Behavior

As soon as I attempt to set `value` to `query`, `handleSearch` seems to be blocked and isn't called (possibly being debounced?)

An extension to the odd behaviour is that it's not limited to setting `query` to `value`, but also other things such as `Math.random().toString()` cause `handleSearch` to be fired _sometimes_. This is strange because hard boolean values seem to work, which is why setting `isLoading` to `true` has no issue. Assinging calculated boolean values to `value` however (such as `Math.random() > 0.5`) bring back the inconsistent experience again.

As soon as you remove `setValue(query)` from `onInputChange`, everything works as expected.

**Comment by ericgio** [comment] 2023-03-02 07:07
Hi @SteppingHat, thanks for filing this issue! I believe this is a duplicate of #561. `setValue` is triggering a re-render, which updates `onSearch`. You need to wrap `onSearch` with `useCallback` to keep it stable. Please refer to [this more in-depth description](https://github.com/ericgio/react-bootstrap-typeahead/issues/561#issuecomment-650454677) of the problem and solution.

**Closed by ericgio** 2023-03-02 07:07 UTC
Labels: bug

**Comment by SteppingHat** [comment] 2023-03-02 07:34
Thank you for the clarification!

**Comment by SteppingHat** [comment] 2023-03-02 07:34
Awesome! Thank you for clarifying! 😄
