### ISSUE TITLE
Including React 0.14 as a dependency breaks in any other version of react

### ISSUE THREAD

**Issue by donnycrash** [ericgio/react-bootstrap-typeahead#20] opened 2016-05-20 09:50 UTC
Hey great job on the component.
Wouldn't it make more sense adding react and react-dom as peerDedependencies in order to prevent it from throwing ref errors

**Comment by ericgio** [comment] 2016-05-20 09:52
Yep, this is a duplicate of https://github.com/ericgio/react-bootstrap-typeahead/issues/18

**Closed by ericgio** 2016-05-20 09:52 UTC
Labels: duplicate
