### ISSUE TITLE
Single selection effect card

### ISSUE THREAD

**Issue by Angelk90** [ericgio/react-bootstrap-typeahead#457] opened 2019-06-19 04:50 UTC
**Is your feature request related to a problem? Please describe.**
In the case of Single selection, when I start to write the name to search for, names appear and I select one, the name is added to the input field.
But if I accidentally press the delete key, the last letter of the name is deleted, in this case the name remains in the input field minus the last letter but is not considered as an element because it has been deleted. And one mistakenly disregards it, must make the relevant checks.

**Describe the solution you'd like**
The solution I propose would be to add the possibility of having the card in the case of single selection, see image to understand.
Possibly with the possibility if you want the card to be extended for the entire length of the input field, so the user will not think he can insert other elements.

**Additional context**
![Screenshot_2019-06-19 React Bootstrap Typeahead Example](https://user-images.githubusercontent.com/20476002/59737126-ac7c8900-925c-11e9-93d4-add6f2e71063.png)
![index](https://user-images.githubusercontent.com/20476002/59737583-79d39000-925e-11e9-8f2e-6b5498dac24a.png)

**Comment by ericgio** [comment] 2019-06-19 17:39
Hi @Angelk90 and thanks for taking the time to file this feature request. I think the solution you're proposing would work for your case but it is pretty specific, so I'm not sure it makes sense to incorporate into the library.

It sounds like the problem you're describing is that the selected vs. non-selected state could be clearer for the single-select version. I see a couple approaches you could take:

1) Use styling of the input to signal that a selection has been made (or not). For example, change the background color of the input when there is a selection.
2) v4 of the library (still in alpha) introduces a `renderInput` method that would provide total flexibility in how the input behaves when selected.

Hope that helps.

**Comment by Angelk90** [comment] 2019-06-19 19:16
@ericgio  : I don't know if it happened to you, try this in the single-selection input field, write something, select an element and stay with the focus still fixed on the field, then web card fields and then return to the card with the input field, not  asks you to select the searched item again?

**Comment by ericgio** [comment] 2019-06-19 19:24
@Angelk90: Sorry, but I don't understand the issue you're describing. Do you believe it's a bug? More detailed repro steps, a sandbox that reproduces the behavior, or both would be helpful. Thanks!

**Comment by Angelk90** [comment] 2019-06-20 16:02
@ericgio : Let me explain better the problem I encountered, go to the following link:
http://ericgio.github.io/react-bootstrap-typeahead/#basic-example

In the input field, select any element of the field remaining the focus on the input field, then change the browser card screen and then return to the card screen where the input field is located.
It will ask you to select a new item.

For the request I made to you I took a look at renderInput, looking at:
https://codesandbox.io/s/4w01px4z6x
But I don't understand why we can't extend the use we make for multiselection even in the case of the single selection.
What I need is only the graphic effect of the tab within the input field if an element is selected.

**Comment by ericgio** [comment] 2019-06-20 18:45
> It will ask you to select a new item.

Yeah it seems that when you return to the original browser tab the browser returns focus to the input, which opens the menu again. I don't really see anything wrong with this.

> What I need is only the graphic effect of the tab within the input field if an element is selected

I would recommend using styling to change the graphic effect, then.

**Comment by Angelk90** [comment] 2019-06-21 05:44
@ericgio : I'm trying to figure out how to use renderInput, but if I simply wanted to customize the ui of the element that is inserted in the input field how can I do?

**Comment by ericgio** [comment] 2019-06-24 04:30
@Angelk90: you can customize the token in the multi-select version using `renderToken`. Please see [the example](http://ericgio.github.io/react-bootstrap-typeahead/#rendering).

**Comment by ericgio** [comment] 2019-06-26 17:10
Closing this issue, since it's not something I'm likely to implement and there are existing solutions.

**Closed by ericgio** 2019-06-26 17:10 UTC
Labels: feature request
