### ISSUE TITLE
No event passed to `onChange`

### ISSUE THREAD

**Issue by Mioleris** [ericgio/react-bootstrap-typeahead#494] opened 2019-10-10 12:37 UTC
Hello all.

Why on `onChange` method only returns value but `onInputChange` returns value and event?

`onChange` - when you select item
`onInputChange` - when you type (**when value changes**)

But when you select item from the list this event `onInputChange`  is not called but actual **value changed** and `onChange` method is called

How to capture event when user selects item ?

**Comment by ericgio** [comment] 2019-10-14 17:58
Hi @Mioleris, thanks for your question. This has been discussed in several issues in the past.

`onChange` isn't truly [an event](https://developer.mozilla.org/en-US/docs/Web/API/Event), but a hook into the component's behavior. It's called when selections change **in response to user actions**, which might happen due to an underlying click or keyboard event. 

`onInputChange` is (more or less) the change event on the input of the component, so it does pass the event to the callback. For legacy API reasons, it also passes the value. As you note, it is not fired when `onChange` is called because the value changes programmatically in that case, which is consistent with how an `input` works.

There's definitely been some confusion and discussion about this API over time. For example, should `onChange` become something like `onSelect` so people don't expect an event? Should `onInputChange` then become `onChange` and pass only the event?

Ultimately, I haven't changed the API because people seem to quickly understand it and can do what they need. My sense is therefore that updating the names and callback signatures would be a significant breaking change without a ton of upside.

**Comment by ericgio** [comment] 2019-10-14 18:00
Duplicate of #202

**Closed by ericgio** 2019-10-14 18:00 UTC
Labels: discussion
