### ISSUE TITLE
After deleting a token and emptying the Typeahead form, clicking on the placeholder text does not show the dropdown list

### ISSUE THREAD

**Issue by jsplaine** [ericgio/react-bootstrap-typeahead#232] opened 2017-09-20 14:03 UTC
### Version
^1.4.2

### Steps to reproduce
Visit the demo: http://ericgio.github.io/react-bootstrap-typeahead/#behaviors
* Using the Typeahead box under the Behaviors title, click on "Choose a state..."
* Add a state
* Delete the state
* Click on "Choose a state..." and choose another state
* Note: It doesn't work, to re-select a state, you have to either first click outside the Typeahead box, and then click back in -- or by clicking somewhere to the right of the "Choose a state..." hint text.

### Expected Behavior
* You should be able to delete a value and, by clicking on the placeholder text ("Choose a state..."), be presented the dropdown again.

### Actual Behavior
* It doesn't work, to re-select a state, you have to either click outside the Typeahead box, and then click back in.  Or click somewhere to the right of the "Choose a state..." hint text.

**Comment by ericgio** [comment] 2017-09-20 16:40
Dupe of #217

**Closed by ericgio** 2017-09-20 16:40 UTC
Labels: duplicate
