### ISSUE TITLE
Partially typed selection options are not selectable if click is on text span in 2.0.0-alpha.3

### ISSUE THREAD

**Issue by pumpadump** [ericgio/react-bootstrap-typeahead#241] opened 2017-10-06 10:28 UTC
### Version
2.0.0-alpha.3
### Steps to reproduce
1. Create a Typeahead compontent and supply some options.
2. Type some partially matching text into the component
3. Click on the text of a suggested selection option
### Expected Behavior
The option should be selected and the onchange listener should be called
### Actual Behavior
Nothing happens

If you click outside of the text in the line of the suggested element that the selection works as expected. Same if you don't type at all an just select an option.

This bug does not affect 1.4.2

**Comment by ericgio** [comment] 2017-10-07 01:23
Thanks for the report; seems like a duplicate of #219

**Closed by ericgio** 2017-10-07 01:23 UTC
Labels: duplicate
