### ISSUE TITLE
Long option causes menu to open in wrong position

### ISSUE THREAD

**Issue by Vikciux** [ericgio/react-bootstrap-typeahead#776] opened 2023-03-16 13:19 UTC
### Version
6.0.2

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-typeahead-bug-with-long-labels-ix81kd
2. open typeahead menu
3. notice that menu is shifted to the left edge of the view
4. start scrolling options and notice that menu position fixes itself

### Expected Behavior
Menu is aligned with input when opened.

### Actual Behavior

Menu is shifted to the left edge of the view once opened. Menu position gets fixed once you start scrolling.

I can reproduce it with Chrome and FF.

![Capture](https://user-images.githubusercontent.com/6037993/225629167-f841e12d-5a65-416b-8996-631c37bdb475.PNG)

**Comment by ericgio** [comment] 2023-03-22 05:19
Hey @Vikciux thanks for the report and the sandbox reproducing the issue. It looks like the issue reproduces even without a long menu item label if you make the window narrower and try to re-open the menu. Seems like the popper might be getting stale reference element dimensions or something.

**Comment by Vikciux** [comment] 2023-04-24 05:23
Thanks for the great component! Providing a comprehensive report is the least I can do.

Any idea when we can expect a fix?

**Comment by ericgio** [comment] 2023-04-25 19:02
@Vikciux I don't have a timeframe for a fix at the moment. If you'd like to spend some time pinpointing the issue or even submitting a fix, that'd be helpful :)

**Comment by mistahoward** [comment] 2023-08-18 22:25
I was having a lot of issues getting typeahead to build locally for me to test and debug. Looks like popper dropdown menu inset isn't set correctly. If you modify the inline css for inset-right to auto on the dropdown menu, it's correctly aligned. YMMV.

**Comment by BlackLanzer** [comment] 2024-09-02 10:31
Hello,

did anyone find a solution?

**Comment by ericgio** [comment] 2024-11-30 05:25
This should be fixed in v6.3.3

**Closed by ericgio** 2024-11-30 05:25 UTC
Labels: bug
