### ISSUE TITLE
Unable to show menu always

### ISSUE THREAD

**Issue by xyogol** [ericgio/react-bootstrap-typeahead#374] opened 2018-08-31 07:21 UTC
Feature requests
=======================

Hello, maybe I am missing something in the docs, because I cannot make the Typeahead to be visible always without the input focus, I've tried adding showMenu={true} and isMenuShown={true} props on the Typeahead component, but menu is still not visible.

**Comment by ericgio** [comment] 2018-08-31 17:42
That's correct, the public API does not currently expose a way to control menu visibility. I'm going to close this a a duplicate of #325. Can you please comment there with more info about your use case?

**Closed by ericgio** 2018-08-31 17:42 UTC
