### ISSUE TITLE
Tabbing on a focused input should fill the input with the current value

### ISSUE THREAD

**Issue by cephirothdy2j** [ericgio/react-bootstrap-typeahead#126] opened 2016-12-22 21:18 UTC
This looks to have been addressed [here](https://github.com/ericgio/react-bootstrap-typeahead/pull/35) but is not currently implemented in v1.0.0beta4.

See attached. On focusing the input ...

1. I type "acc", which displays a list of relevant options.
2. I use my down / up arrow keys to select the option I want. This highlights the options one by one in the list and, at the same time, fills my input with the content of the selected option.
3. When I've chosen the correct option, I push my "Tab" key to move to the next input.

Expected behavior:
The value of my chosen option, which displays in the input and as selected in the dropdown, would be my input's value as I tab to the next field.

Actual behavior:
The value of the original input reverts to the value I originally typed ("acc").

<img width="371" alt="screen shot 2016-12-22 at 4 11 35 pm" src="https://cloud.githubusercontent.com/assets/881769/21440531/6e04a97c-c861-11e6-9a7c-414492009eee.png">

**Comment by ericgio** [comment] 2016-12-22 21:34
I think the PR you're referencing and what I implemented may be slightly different. 0.6.3 added autocompletion on tab when there's a hint (and the input is still focused), whereas it sounds like you're asking for tab selection when a menu item is active.

**Comment by ericgio** [comment] 2016-12-22 21:38
I'm seeing a slightly different behavior than what you're describing when I try it on the example. For me, tabbing with an active menu item selects that item and closes the menu, but retains focus on the input. I then need to hit tab again to move to the next input.

**Comment by cephirothdy2j** [comment] 2016-12-22 21:44
I see the same behavior in the examples. I wonder if there's something I'm doing wrong, though everything else works as I want.

Here is a (shortened) code sample. Please let me know if anything jumps out at you ...

`
import React, { Component } from 'react';

import {Typeahead} from 'react-bootstrap-typeahead';

class SelectTypeahead extends Component {
  constructor(props) {
    super(props);
    this.state = {};
    this._handleChange = this._handleChange.bind(this);
    this._handleInputChange = this._handleInputChange.bind(this);
    this._convertValue = this._convertValue.bind(this);
  }

  _handleChange(selection) {
    console.log('change', selection);
    const { multiple, onChange, allowNew } = this.props;

    // if we're allowing new creations and NOT allowing multiple selections,
    // we're handling the form update in the _handleInputChange method
    if(multiple || !allowNew) {
      let selections = selection || [];
      if(allowNew) { // new options come through as an object
        selections = (selection).map((item) => {
          if(item && item.label) return item.label;
          return item;
        });
      }

      if(!multiple){ // result is always returned as an array
        onChange(selections && selections[0]);
      } else {
        onChange(selections);
      }
    }
  }

  _handleInputChange(selection) {
    console.log('input', selection);
    const {multiple, onChange, allowNew} = this.props;
    if(!multiple && allowNew) {
      onChange(selection);
    }
  }

  _convertValue() {
    const {multiple, value} = this.props;
    if(!multiple) {
      return [value];
    } else {
      return value;
    }
  }

  render() {

    const options = [
      {value:'Accept', label: 'Accept'},
      {value:'Accept-Charset', label: 'Accept-Charset'},
      {value:'Accept-Encoding', label: 'Accept-Encoding'},
      {value:'Accept-Language', label: 'Accept-Language'},
      {value:'Accept-Datetime', label: 'Accept-Datetime'},
      {value:'Authorization', label: 'Authorization'}
    ];

    return (
        <Typeahead
          onChange={this._handleChange}
          onInputChange={this._handleInputChange}
          allowNew={true}
          multiple={false}
          clearable={false}
          newSelectionPrefix={''}
          options={options}
          selected={this._convertValue()} />
    );
  }
}

export default SelectTypeahead;

`

**Comment by ericgio** [comment] 2016-12-22 21:53
It looks like you're currently passing the results of `this._convertValue` to `selected` rather than passing the function itself. I also don't think you need `this._handleInputChange`, since that's just a way to respond to what the user is actively typing.

Separately, `clearable` isn't a valid prop (I think you want `clearButton`?)

**Comment by cephirothdy2j** [comment] 2016-12-22 22:01
Per your documentation, I can only pass an array to `selected`, which is why I'm passing the result instead of the function.

Removing `this._handleInputChange` brings my component's behavior in line with your example page, but it then creates a new issue. This too cannot be recreated in your example page ...

1. I focus the input and type nothing. The focused input, by default, shows the typeahead menu with all options.
2. I arrow down to the option I want to select.
3. I hit tab when I have selected my option.

Expected behavior:
The selected option is set to the input's value.

Actual behavior:
The input's value is blank.

**Comment by ericgio** [comment] 2016-12-22 22:14
Sorry, I was totally confused and thought for a second that `select` takes a callback. You're absolutely right. 

Did you update the logic in `_handleChange`? It looks like you were ignoring certain cases and handling with `_handleInputChange` instead.

**Comment by ericgio** [comment] 2016-12-22 22:19
Yeah it looks like `_handleChange` is currently a no-op, since `multiple` and `!allowNew` are both false, thus skipping that entire block.

**Comment by mvolkmann** [comment] 2017-01-06 17:49
I think I'm wanting the same behavior that was described earlier. If the user types enough to narrow the options to one and then presses tab, I'd like that value to be selected. For example, if I type "gor" and that only matches "gorilla", I'd like to be able to press tab and have it select "gorilla".

Is this the way it is intended to work?

**Comment by mvolkmann** [comment] 2017-01-06 18:37
I found a way to get what I want based on a post in another issue from @daschi.
````
  fixTypeahead() {
    const {container} = this;
    if (!container) return;

    const input = container.querySelector('input');
    if (input.onkeydown) return; // don't need to set this up again

    input.onkeydown = event => {
      if (event.keyCode !== 13) return;
      const items = container.querySelectorAll('.bootstrap-typeahead-menu > li');
      if (items.length === 1) items[0].querySelector('a').click();
    };
  }
````
I call this from `componentDidMount` and `componentDidUpdate`.

I wrap my Typeahead in a div like this:
````
<div ref={saveTypeahead}> ... </div>
````
And here is saveTypeahead:
````
const saveTypeahead = c => this.container = c;
````

**Comment by ericgio** [comment] 2017-01-14 01:28
@cephirothdy2j: were you able to figure out your issue?
@mvolkmann: it sounds like what you're talking about is being tracked in https://github.com/ericgio/react-bootstrap-typeahead/issues/77.

**Comment by mvolkmann** [comment] 2017-01-14 04:05
Yes. The solution I described is working great for me. I would be nice if that was a built-in option.

**Comment by cephirothdy2j** [comment] 2017-01-16 15:14
Not yet, but I sort of dropped the issue for now and moved on to other things. Thanks for your help so far.

**Comment by ericgio** [comment] 2017-02-18 05:41
Closing this issue as not a bug; as mentioned above the "tab-to-select" functionality already exists. The other issue of highlighting the only option is already being tracked in #77.

**Closed by ericgio** 2017-02-18 05:41 UTC
Labels: not a bug
