### ISSUE TITLE
Warning: flushSync was called from inside a lifecycle method

### ISSUE THREAD

**Issue by jakajancar** [ericgio/react-bootstrap-typeahead#715] opened 2022-05-02 21:17 UTC
### Version

6.0.0-alpha.11

### Steps to reproduce

It happens in a fairly large project, but not on CodeSandbox sample, and I did not have time to bisect properly. If it's obvious to you what the issue is, great, otherwise feel free to close and I will re-open when I have a better repro.

Fwiw, it does not happen with 5.x.

### Actual Behavior

```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
Menu2
Overlay2
div
RootClose2
TypeaheadManager2
Typeahead2
TypeaheadComponent2
MyComponent
```

**Comment by jimbglenn** [comment] 2022-05-02 22:00
I actually just found this library and installed it today in one of our projects.
I was also on the 6.* alpha, and also received a flushSync error on mine:

```

[Error] Error: flushSync was called from inside a lifecycle method. It cannot be called when React is already rendering.
	flushSync (1.chunk.js:88127:134)
	fn (19.chunk.js:8521)
	forceUpdate (1.chunk.js:15037)
	(anonymous function) (19.chunk.js:2210)
	commitHookEffectListMount (1.chunk.js:85959)

```

Downgrading I was able to get a basic auto-suggest to work.

**Comment by ericgio** [comment] 2022-05-03 03:47
Thanks for opening this issue! If either of you can help out by providing a minimal repro, I can try to have a look.

**Comment by sushantdhiman** [comment] 2022-05-16 08:18
Similar issue in my project as well. Sample test which passed but gave this warning

```js
it('blur calls onChange with input text', async function () {
    render(<Input {...this.props} />);
                                    
    const input = screen.getByPlaceholderText(
      '---------------',
    );
                                       
    fireEvent.change(input, { target: { value: 'test' } });
    fireEvent.blur(input); // focus lost
                                  
    expect(this.props.onChange.firstCall.firstArg, 'to exhaustively satisfy', [
      'test',
    ]);
  });
```

```js
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
    at Menu (---------------/node_modules/react-bootstrap-typeahead/cjs/components/Menu/Menu.js:84:23)
    at TypeaheadMenu (---------------/node_modules/react-bootstrap-typeahead/cjs/components/TypeaheadMenu/TypeaheadMenu.js:55:24)
    at Overlay (---------------/node_modules/react-bootstrap-typeahead/cjs/components/Overlay/Overlay.js:99:31)
    at div
    at RootClose (---------------/node_modules/react-bootstrap-typeahead/cjs/components/Typeahead/Typeahead.js:150:23)
    at TypeaheadManager (---------------/node_modules/react-bootstrap-typeahead/cjs/core/TypeaheadManager.js:35:24)
    at Typeahead (---------------/node_modules/react-bootstrap-typeahead/cjs/core/Typeahead.js:315:37)
    at TypeaheadComponent (---------------/node_modules/react-bootstrap-typeahead/cjs/components/Typeahead/Typeahead.js:171:37)
```

**Comment by exotexot** [comment] 2022-05-18 16:09
Have the same issue with 6.0.0-alpha.11
Issue is reproducible with the demo code: http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching

**Comment by nativeforest** [comment] 2022-06-06 16:32
same here, i am using AsyncTypehead component who receive props and get this warning log 

**Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
Menu@http://localhost:3000/static/js/bundle.js:114522:18
TypeaheadMenu@http://localhost:3000/static/js/bundle.js:115260:18
Overlay@http://localhost:3000/static/js/bundle.js:114720:26
div
RootClose@http://localhost:3000/static/js/bundle.js:115526:18
TypeaheadManager@http://localhost:3000/static/js/bundle.js:116579:18
Typeahead@http://localhost:3000/static/js/bundle.js:116145:86
TypeaheadComponent@http://localhost:3000/static/js/bundle.js:115547:86
./node_modules/react-bootstrap-typeahead/es/behaviors/async.js/withAsync/AsyncTypeahead<@http://localhost:3000/static/js/bundle.js:113600:181**

**Comment by dnsnx** [comment] 2022-06-09 05:58
Yeah, same issue here. I'm using React 18 with react-bootstrap-typeahead vers. 6.0.0-rc.1.
This is the code I'm using:

```
function Address(props) {

    function filterCountries(option, props) {
        option.name.toLowerCase().indexOf(props.text.toLowerCase()) !== -1
    }

    return (
        <FadeIn>
            ...
            <div className="row mt-2">
                <div className="col">
                    <Typeahead
                        filterBy={filterCountries}
                        id="countries"
                        caseSensitive={false}
                        ignoreDiacritics={true}
                        options={props.countries}
                        placeholder="Country"
                    />
                </div>
            </div>
        </FadeIn>
    );
}

```

The data for the select box is a list of countries as you can see here:

![2022-06-09 07_53_17-Clipboard](https://user-images.githubusercontent.com/20823625/172774444-fb032143-d9fb-4e8b-b556-b6848c8af967.png)

When I start typing / filtering the error is being thrown:

> react_devtools_backend.js:4026 Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
>     at Menu (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/Menu/Menu.js:77:23)
>     at TypeaheadMenu (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/TypeaheadMenu/TypeaheadMenu.js:52:24)
>     at Overlay (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/Overlay/Overlay.js:94:31)
>     at div
>     at RootClose (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/Typeahead/Typeahead.js:142:23)
>     at TypeaheadManager (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/core/TypeaheadManager.js:26:24)
>     at Typeahead (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/core/Typeahead.js:307:86)
>     at TypeaheadComponent (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/Typeahead/Typeahead.js:163:86)
>     at div
>     at div
>     at div
>     at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>     at Address (webpack-internal:///./resources/assets/js/components/managementInterface/shop/tabs/wizard/address.component.js:40:66)
>     at ErrorBoundary (webpack-internal:///./resources/assets/js/components/error/error.component.js:41:5)
>     at ComponentWithErrorBoundary (webpack-internal:///./resources/assets/js/components/managementInterface/shop/tabs/wizard/address.component.js:239:23)
>     at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
>     at div
>     at div
>     at BusinessSetupWizard (webpack-internal:///./resources/assets/js/components/managementInterface/shop/tabs/businessSetupWizard.component.js:55:66)
>     at ErrorBoundary (webpack-internal:///./resources/assets/js/components/error/error.component.js:41:5)
>     at ComponentWithErrorBoundary (webpack-internal:///./resources/assets/js/components/managementInterface/shop/tabs/businessSetupWizard.component.js:304:23)
>     at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
>     at div
>     at ProductsManagementContainer (webpack-internal:///./resources/assets/js/containers/managementInterface/productsManagement.container.js:47:66)
>     at ErrorBoundary (webpack-internal:///./resources/assets/js/components/error/error.component.js:41:5)
>     at ComponentWithErrorBoundary (webpack-internal:///./resources/assets/js/containers/managementInterface/productsManagement.container.js:128:23)
>     at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
>     at div
>     at div
>     at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>     at LandingPageEditorView (webpack-internal:///./resources/assets/js/views/editor/landingPageEditor.view.js:104:5)
>     at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:234:68)
>     at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:19:20)

Maybe it helps to find the error.

**Comment by bymagnum** [comment] 2022-06-19 18:39
I use:

<AsyncTypeahead
    id="async-example"
    filterBy={filterBy}
    isLoading={isLoading}
    onSearch={handleSearch}
    options={options}
/>

Error:

next-dev.js?3515:25 Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
    at Menu (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/Menu/Menu.js:74:23)
    at TypeaheadMenu (webpack-internal:///./node_modules/react-bootstrap-typeahead/es/components/TypeaheadMenu/TypeaheadMenu.js:49:24)
......

**Comment by mjakal** [comment] 2022-06-24 13:55
Same thing is happening to me. You can reproduce it by opening the dropdown menu.

react: 17.0.2
react-bootstrap-typeahead: 6.0.0-rc.2
react-scripts: 4.0.3

Example

```
import React, { useState } from 'react';
import { Typeahead } from 'react-bootstrap-typeahead';

const userList = [
  {
    id: 0,
    name: 'User 1',
  },
  {
    id: 1,
    name: 'User 2',
  },
  {
    id: 2,
    name: 'User 3',
  },
];

const UserList = () => {
  const [user, setUser] = useState([]);

  return (
    <Typeahead
      id="user"
      labelKey="name"
      multiple
      onChange={(value) => setUser(value)}
      options={userList}
      placeholder="Select Users..."
      selected={user}
    />
  );
};

export default UserList;
```

**Comment by ericgio** [comment] 2022-06-24 16:32
@mjakal interesting, I think this may be a conflict with react-scripts. I can repro the error in a sandbox that uses that package, but not locally in a manually generated React environment.

**Comment by ericgio** [comment] 2022-07-04 08:29
I _think_ this should be fixed in v6.0.0-rc.3; I can no longer repro the issue in a sandbox using that version. I believe the issue was caused by `Menu` inadvertently calling PopperJS's `forceUpdate` function on every render, which shouldn't happen any more.

**Closed by ericgio** 2022-07-04 08:29 UTC
Labels: bug

**Comment by sabhisingh26** [comment] 2023-04-29 01:55
Able to reproduce this issue with new version

**Comment by hanorine** [comment] 2023-05-30 19:35
I am also having the same error occurring with `react-bootstrap-typeahead@6.2.2`. I don't recall seeing this issue in previous releases.

**Comment by sabhisingh26** [comment] 2023-06-29 18:56
Able to fix this with custom dropdown.

**Comment by kante-srikanth** [comment] 2023-08-29 04:08
I am also having the same error occurring with react-bootstrap-typeahead@6.2.2
